# Default config file should have all key values 
# with the default value that can be used for config files that does not define it

[devices]
use_fake = false
fake_device_location = "."
fake_device_type=""
